### PR TITLE
Feature/scrapper

### LINKED ISSUE #3: Create scrapper
Zespół utworzył skrypt/program to scrapowania (automatycznego odczytania i zapisania lokalnie informacji/danych z wybranego sklepu internetowego).

- [x] Kod źródłowy rozwiązania znajduje się w repozytorium;
- [x] Rezultaty scrappowania (kodowanie UTF-8) znajdują się w folderze w repozytorium,
- [x] Rezultatami scrappowania są m.in. listy kategorii, podkategorii, produktów (nazwa, opis, cena, atrybuty (np. kolor, materiał), dwa zdjęcia w rozdzielczości która umożliwia wyświetlenia ostrego zdjęcia po powiększeniu w sklepie)

### PR DESCRIPTION
**Pull request by Ewikk**
Scrapper and data loader implemented.

Both scrapper and data loader must be run from scrapper/src directory by default. This behaviour can be changed by modifying scrapped files' directory in scrapper/src/config.py

Data loader requires enabling prestashop's web services in admin panel, generating api key and pasting it into scrapper/src/config.py.

Python libraries required to run scrapper: bs4, pandas, requests, csv.

Python libraries required to run data loader: prestapyt, pandas, opencv-python

closes #3

### CODE REVIEW

**Comment by blazej222** [comment]
Config:
```
Go in the PrestaShop back office, open the “Web service” page under the “Advanced Parameters” menu, and then choose “Yes” for the “Enable PrestaShop Webservice” option.
Then click add new webservice key
```

It would be nice to know which API permissions exactly are needed for dataLoader (to avoid generating key with all possible permissions)

**Review by blazej222 — CHANGES_REQUESTED** [review]
Data loader fails with

```
Traceback (most recent call last):
  File "/home/blazej/repo/scrapper/src/dataLoader.py", line 173, in <module>
    addCategories()
  File "/home/blazej/repo/scrapper/src/dataLoader.py", line 46, in addCategories
    addCategory(row['Name'], parentID)
  File "/home/blazej/repo/scrapper/src/dataLoader.py", line 63, in addCategory
    category_schema["category"]["name"]["language"]["value"] = name
TypeError: list indices must be integers or slices, not str
```

Please fix before merging.

**Comment by Ewikk** [comment]
Scrapper results are in Polish only, so data loader requires prestashop to have only one active language - Polish.
You can add/remove lanugages in admin panel under International/Localization/Languages.
In order to remove every language except Polish, page's default language must be set to Polish. It can be done in International/Localization. A profile language should be set to Polish as well, profile settings are located in the top right corner in the admin panel

**Comment by blazej222** [comment]
Language identifier should also be changed to pl.

**Review by blazej222 — DISMISSED** [review]
Approved.

**Comment by Ewikk** [comment]
Data loader now needs additional library: opencv-python

**Review by blazej222 — APPROVED** [review]
Approve. Pending bugfixes will be merged via another PR.

**Comment by PiotrexOG** [comment]
Traceback (most recent call last):
  File "/home/piotr/Online-shop/scrapper/src/dataLoader.py", line 7, in <module>
    import cv2
  File "/home/piotr/.local/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/piotr/.local/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Solution:
sudo apt install libgl1-mesa-glx

**Pull request merged**
